### ISSUE TITLE
Escape line breaks in export to CSV

### ISSUE THREAD

**Issue by spbagshaw** [spc-ofp/tubs-web-reporting#8]
Can use REPLACE(col_name, char(13)+char(10), ' ')

**Comment by brunodeprez** [comment]
Steve, any particular report where I could try that?

Thanks

**Comment by spbagshaw** [comment]
If you look at the query for artisanal report #101 (enabled for CK), you can see where I needed to escape both commas and line breaks for various fields.

**Comment by brunodeprez** [comment]
Fixed with the previous commit  5601ffcf37c0a1e9ca43581db11e9811eae278bf
